-- Populate some seed data into the SRDEMO tables
-- $Id: populateSchemaTables.sql,v 1.5 2005/12/22 22:46:41 duncan Exp $


Insert into products values (100,'Washing Machine W001',null,'1000 spin, A Energy at 40 Deg., 11lb/5kg capacity');
Insert into products values (101,'Washing Machine W003a',null,'1200 spin, A+ Energy at 40 Deg., 15lb/6kg capacity');
Insert into products values (102,'Washing Machine W017',null,'1400 spin, A Energy at 40 Deg., 11lb/5kg capacity');
Insert into products values (103,'Washing Machine T006',null,'Twin Tub, 800 spin, C Energy at 40 Deg., 10lb/4.5kg capacity');
Insert into products values (104,'Washer Dryer W001d',null,'1000 spin, A Energy at 40 Deg., 11lb/5kg capacity, 9lb/4kg drying capacity');
Insert into products values (105,'Washer Dryer W003d',null,'1200 spin, A+ Energy at 40 Deg., 15lb/6kg capacity, 11lb/5kg drying capacity');
Insert into products values (106,'Washer Dryer W017d',null,'1400 spin, A Energy at 40 Deg., 11lb/5kg capacity, 11lb/5kg drying capacity');
Insert into products values (107,'Dryer D003',null,'Vented, B+ Energy, 15lb/6kg capacity');
Insert into products values (108,'Dryer D011',null,'Condensing, A Energy, 11lb/5kg capacity');
Insert into products values (109,'Fridge F011s',null,'7.5 CUFT, A+ Energy, FF, Auto-Defrost, Silver');
Insert into products values (110,'Fridge F011w',null,'7.5 CUFT, A+ Energy, FF, Auto-Defrost, White');
Insert into products values (111,'Fridge F011b',null,'7.5 CUFT, A+ Energy, FF, Auto-Defrost, Black');
Insert into products values (112,'Fridge F004w',null,'4.5 CUFT, Under Counter, A++ Energy, FF, Auto-Defrost, White');
Insert into products values (113,'Fridge Freezer FZ007s',null,'4.5 / 1.5  CUFT, A+ Energy, FF, Auto-Defrost, Silver');
Insert into products values (114,'Fridge Freezer FZ007w',null,'4.5 / 1.5  CUFT, A+ Energy, FF, Auto-Defrost, White');
Insert into products values (115,'Freezer Z002s',null,'7.5 CUFT, A Energy, FF, Silver');
Insert into products values (116,'Freezer Z002w',null,'7.5 CUFT, A Energy, FF, White');
Insert into products values (117,'Freezer Z002b',null,'7.5 CUFT, A Energy, FF, Black');
Insert into products values (118,'Chest Freezer Z001w',null,'12.5 CUFT, B+ Energy, White');
Insert into products values (119,'Ice Maker I012',null,'30lb capacity storage bin, FF');


Insert into users values (300,'manager','sking','Steven','King','2004 Charade Rd','Seattle','Washington','98199','US');
Insert into users values (301,'user','nkochhar','Neena','Kochhar','400 E Joppa Rd','Baltimore','Maryland','21286','US');
Insert into users values (302,'user','ldehaan','Lex','De Haan','1796 Tsing Tao','Muang Nonthaburi','','11111','CN');
Insert into users values (303,'technician','ahunold','Alexander','Hunold','2014 Jabberwocky Rd','Southlake','Texas','26192','US');
Insert into users values (304,'technician','bernst','Bruce','Ernst','2014 Jabberwocky Rd','Southlake','Texas','26192','US');
Insert into users values (305,'technician','daustin','David','Austin','2014 Jabberwocky Rd','Southlake','Texas','26192','US');
Insert into users values (306,'technician','vpatabal','Valli','Pataballa','2014 Jabberwocky Rd','Southlake','Texas','26192','US');
Insert into users values (307,'technician','dlorentz','Diana','Lorentz','2014 Jabberwocky Rd','Southlake','Texas','26192','US');
Insert into users values (308,'user','ngreenbe','Nancy','Greenberg','1810 Tucker Crt','Mumbai','Kar','361181','IN');
Insert into users values (309,'user','dfaviet','Daniel','Faviet','932 High St','Lancaster','Pennsylvania','17603','US');
Insert into users values (310,'user','jchen','John','Chen','1971 Limelight Blvd','Samutprakarn','','','TH');
Insert into users values (311,'user','isciarra','Ismael','Sciarra','Via Luminosa 162','Firenze','','361197','IT');
Insert into users values (312,'user','jmurman','Jose Manuel','Urman','Walpurgisstr 69','Munich','','81243','DE');
Insert into users values (313,'user','lpopp','Luis','Popp','Harmoniegasse 3','Baden-Daettwil','AG','3413','CH');
Insert into users values (314,'user','drapheal','Den','Raphaely','301 E Genesee Ave','Detroit','Michigan','48206','US');
Insert into users values (315,'user','akhoo','Alexander','Khoo','10315 Hickman Rd','Des Moines','Iowa','50322','US');
Insert into users values (316,'user','sbaida','Shelli','Baida','4715 Sprecher Rd','Madison','Wisconsin','53704','US');
Insert into users values (317,'user','eclabe','Emerson','Clabe','1118 Poplarwood Court','Orlando','Florida','32829','US');
Insert into users values (318,'user','ghimuro','Guy','Himuro','2720 Brewerton Rd','Syracuse','New York','13211','US');
Insert into users values (319,'user','kcolmena','Karen','Colmenares','1303 E University St','Bloomington','Indiana','47401','US');
Insert into users values (320,'user','jwhalen','Jennifer','Whalen','2800 Chicago Ave # 100','Minnepolis','Minnesota','55407','US');
Insert into users values (321,'user','mhartste','Michael','Hartstein','147 Spadina Ave','Toronto','Ontario','M5V 2L7','CA');
Insert into users values (322,'user','pfay','Pat','Fay','147 Spadina Ave','Toronto','Ontario','M5V 2L7','CA');
Insert into users values (323,'user','smavris','Susan','Mavris','8204 Arthur St','London','','','UK');
Insert into users values (324,'user','hbaer','Hermann','Baer','Schwanthalerstr. 7031','Munich','Bavaria','80925','DE');
Insert into users values (325,'user','shiggins','Shelley','Higgins','726 Union St','Hudson','New York','12534','US');
Insert into users values (326,'user','wgietz','William','Gietz','1126 Pawlings Rd','Norristown','Pennsylvania','19403','US');

Insert into EXPERTISE_AREAS values (100,300,'Expert',null);
Insert into EXPERTISE_AREAS values (100,303,'Qualified',null);
Insert into EXPERTISE_AREAS values (100,304,'Expert',null);
Insert into EXPERTISE_AREAS values (100,305,'Apprentice',null);
Insert into EXPERTISE_AREAS values (100,306,'Expert',null);
Insert into EXPERTISE_AREAS values (100,307,'Expert',null);
Insert into EXPERTISE_AREAS values (101,300,'Expert',null);
Insert into EXPERTISE_AREAS values (101,303,'Qualified',null);
Insert into EXPERTISE_AREAS values (101,304,'Expert',null);
Insert into EXPERTISE_AREAS values (101,306,'Expert',null);
Insert into EXPERTISE_AREAS values (102,300,'Expert',null);
Insert into EXPERTISE_AREAS values (102,303,'Expert',null);
Insert into EXPERTISE_AREAS values (102,304,'Expert',null);
Insert into EXPERTISE_AREAS values (102,305,'Apprentice',null);
Insert into EXPERTISE_AREAS values (102,306,'Qualified',null);
Insert into EXPERTISE_AREAS values (103,300,'Expert',null);
Insert into EXPERTISE_AREAS values (103,303,'Apprentice',null);
Insert into EXPERTISE_AREAS values (103,304,'Expert',null);
Insert into EXPERTISE_AREAS values (104,300,'Expert',null);
Insert into EXPERTISE_AREAS values (104,303,'Expert',null);
Insert into EXPERTISE_AREAS values (104,304,'Expert',null);
Insert into EXPERTISE_AREAS values (104,306,'Expert',null);
Insert into EXPERTISE_AREAS values (104,307,'Expert',null);
Insert into EXPERTISE_AREAS values (105,300,'Expert',null);
Insert into EXPERTISE_AREAS values (105,306,'Qualified',null);
Insert into EXPERTISE_AREAS values (105,307,'Expert',null);
Insert into EXPERTISE_AREAS values (106,300,'Expert',null);
Insert into EXPERTISE_AREAS values (106,304,'Qualified',null);
Insert into EXPERTISE_AREAS values (106,305,'Apprentice',null);
Insert into EXPERTISE_AREAS values (106,306,'Expert',null);
Insert into EXPERTISE_AREAS values (106,307,'Expert',null);
Insert into EXPERTISE_AREAS values (107,300,'Expert',null);
Insert into EXPERTISE_AREAS values (107,304,'Expert',null);
Insert into EXPERTISE_AREAS values (107,305,'Apprentice',null);
Insert into EXPERTISE_AREAS values (107,306,'Expert',null);
Insert into EXPERTISE_AREAS values (107,307,'Expert',null);
Insert into EXPERTISE_AREAS values (108,300,'Expert',null);
Insert into EXPERTISE_AREAS values (108,303,'Expert',null);
Insert into EXPERTISE_AREAS values (108,304,'Qualified',null);
Insert into EXPERTISE_AREAS values (108,307,'Expert',null);
Insert into EXPERTISE_AREAS values (109,300,'Qualified',null);
Insert into EXPERTISE_AREAS values (109,303,'Expert',null);
Insert into EXPERTISE_AREAS values (109,304,'Expert',null);
Insert into EXPERTISE_AREAS values (109,305,'Expert',null);
Insert into EXPERTISE_AREAS values (109,306,'Expert',null);
Insert into EXPERTISE_AREAS values (109,307,'Apprentice',null);
Insert into EXPERTISE_AREAS values (110,300,'Expert',null);
Insert into EXPERTISE_AREAS values (110,304,'Expert',null);
Insert into EXPERTISE_AREAS values (110,305,'Apprentice',null);
Insert into EXPERTISE_AREAS values (110,306,'Qualified',null);
Insert into EXPERTISE_AREAS values (110,307,'Qualified',null);
Insert into EXPERTISE_AREAS values (111,300,'Qualified',null);
Insert into EXPERTISE_AREAS values (111,305,'Qualified',null);
Insert into EXPERTISE_AREAS values (111,306,'Qualified',null);
Insert into EXPERTISE_AREAS values (111,307,'Expert',null);
Insert into EXPERTISE_AREAS values (112,303,'Expert',null);
Insert into EXPERTISE_AREAS values (112,304,'Qualified',null);
Insert into EXPERTISE_AREAS values (112,305,'Apprentice',null);
Insert into EXPERTISE_AREAS values (112,306,'Qualified',null);
Insert into EXPERTISE_AREAS values (112,307,'Expert',null);
Insert into EXPERTISE_AREAS values (113,303,'Expert',null);
Insert into EXPERTISE_AREAS values (113,304,'Qualified',null);
Insert into EXPERTISE_AREAS values (113,305,'Expert',null);
Insert into EXPERTISE_AREAS values (114,300,'Expert',null);
Insert into EXPERTISE_AREAS values (114,304,'Expert',null);
Insert into EXPERTISE_AREAS values (114,306,'Apprentice',null);
Insert into EXPERTISE_AREAS values (115,300,'Expert',null);
Insert into EXPERTISE_AREAS values (115,303,'Expert',null);
Insert into EXPERTISE_AREAS values (115,304,'Expert',null);
Insert into EXPERTISE_AREAS values (115,305,'Apprentice',null);
Insert into EXPERTISE_AREAS values (116,300,'Expert',null);
Insert into EXPERTISE_AREAS values (116,303,'Qualified',null);
Insert into EXPERTISE_AREAS values (116,304,'Expert',null);
Insert into EXPERTISE_AREAS values (117,300,'Expert',null);
Insert into EXPERTISE_AREAS values (117,304,'Qualified',null);
Insert into EXPERTISE_AREAS values (117,305,'Expert',null);
Insert into EXPERTISE_AREAS values (117,307,'Expert',null);
Insert into EXPERTISE_AREAS values (118,300,'Expert',null);
Insert into EXPERTISE_AREAS values (118,306,'Expert',null);
Insert into EXPERTISE_AREAS values (118,307,'Expert',null);
Insert into EXPERTISE_AREAS values (119,307,'Expert',null);

Insert into service_requests values (100,'Closed',sysdate-10,'I have noticed that every time I do a wash there is a pool of water at the back of the machine',100,309,303,sysdate-4);
Insert into service_requests values (101,'Closed',sysdate-20,'Agitator does not work',101,316,304,sysdate-13);
Insert into service_requests values (102,'Pending',sysdate-5,'Washing Machine does not turn on',102,322,304,sysdate-4);
Insert into service_requests values (103,'Closed',sysdate-13,'Washing machine leaks',103,308,307,sysdate-10);
Insert into service_requests values (104,'Open',sysdate-2,'Spin cycle not draining',106,314,305,sysdate-2);
Insert into service_requests values (105,'Closed',sysdate-10,'Air in dryer not hot',107,312,303,sysdate-9);
Insert into service_requests values (106,'Closed',sysdate-24,'Ice machine not working',109,321,300,sysdate-23);
Insert into service_requests values (107,'Pending',sysdate-5,'Fridge is leaking',111,310,306,sysdate-4);
Insert into service_requests values (108,'Open',sysdate-4,'Freezer full of frost',114,317,304,sysdate-2);
Insert into service_requests values (109,'Closed',sysdate-10,'Freezer is not cold',115,320,300,sysdate-9);
Insert into service_requests values (110,'Pending',sysdate-4,'Freezer lid will not fully close',118,318,300,sysdate-3);
Insert into service_requests values (111,'Open',sysdate-2,'Defroster is not working properly',113,325,300,sysdate-1);
Insert into service_requests values (112,'Open',sysdate-2,'My Dryer does not seem to be getting hot',111,310,306,sysdate-4);
Insert into service_requests values (113,'Open',sysdate-1,'I''m getting a strange clicking sound when the washer enters full spin',100,309,null,null);
Insert into service_requests values (114,'Open',sysdate-1,'There seems to be a further problem, I can''t seem to open the door for 5 minutes after the washer cycle has finished',100,309,null,null);


Insert into SERVICE_HISTORIES values (100,1,sysdate-4,'Had customer check hoses to see if they are leaking','Technician',303);
Insert into SERVICE_HISTORIES values (100,2,sysdate-3,'Everything works it was the hose to washing machine connector','Customer',309);
Insert into SERVICE_HISTORIES values (100,3,sysdate-2,'Maybe we should consider a recall on the hoses connectors','Hidden',300);
Insert into SERVICE_HISTORIES values (100,4,sysdate-1,'I have seen this issue before, too and agree a recall is warranted ','Hidden',307);
Insert into SERVICE_HISTORIES values (101,1,sysdate-13,'Asked customer to ensure the lid was closed','Technician',304);
Insert into SERVICE_HISTORIES values (101,2,sysdate-12,'Problem is fixed','Customer',316);
Insert into SERVICE_HISTORIES values (102,1,sysdate-4,'Called customer to make sure washer was plugged in - customer was not by the machine and will call back','Technician',304);
Insert into SERVICE_HISTORIES values (102,2,sysdate-3,'We should modify the setup instructions to include a step to plug in the washer','Hidden',304);
Insert into SERVICE_HISTORIES values (103,1,sysdate-10,'Had customer check hoses to see if they are leaking','Technician',307); 
Insert into SERVICE_HISTORIES values (103,2,sysdate-9,'Hose connectors faulty, shipped new set to customer','Technician',307); 
Insert into SERVICE_HISTORIES values (104,1,sysdate-2,'Researching issue','Technician',305); 
Insert into SERVICE_HISTORIES values (105,1,sysdate-9,'Asked customer to check gas line','Technician',303); 
Insert into SERVICE_HISTORIES values (105,2,sysdate-6,'Gas line was not properly fitted','Customer',312); 
Insert into SERVICE_HISTORIES values (106,1,sysdate-23,'Customer did not have ice machine turned on','Technician',300); 
Insert into SERVICE_HISTORIES values (107,1,sysdate-2,'Customer will call back after checking for clogged drain hoses','Technician',306); 
Insert into SERVICE_HISTORIES values (108,1,sysdate-1,'Researching issue','Technician',304); 
Insert into SERVICE_HISTORIES values (109,1,sysdate-9,'Asked customer to check if freezer is plugged in','Technician',300); 
Insert into SERVICE_HISTORIES values (109,2,sysdate-7,'Freezer is plugged in, please suggest something else','Customer',320); 
Insert into SERVICE_HISTORIES values (109,3,sysdate-7,'Asked customer to set freezer temperature to lowest setting and check after 24 hours','Technician',300); 
Insert into SERVICE_HISTORIES values (109,4,sysdate-6,'Freezer is now cold','Customer',320); 
Insert into SERVICE_HISTORIES values (110,1,sysdate-3,'Asked customer to check the hinges','Technician',300); 
Insert into SERVICE_HISTORIES values (111,1,sysdate-1,'Referring to troubleshooting manual','Technician',300); 
